gentoo:
    image: gentoo/stage3-amd64:latest
#    stdin_open: true # docker run -i
#    tty: true        # docker run -t
    volumes:
        - ./data:/data
    volumes_from:
        - portage
    ports:
        - "8000"
    #privileged: true

portage:
    image: gentoo/portage:latest